name: Deploy React App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: my-react-app/package-lock.json

      - name: Install dependencies
        working-directory: ./my-react-app
        run: npm ci

      - name: Build
        working-directory: ./my-react-app
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload dist
        uses: actions/upload-pages-artifact@v4
        with:
          path: './my-react-app/dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4